### ISSUE TITLE
Cookie does not update dailyRewardClaimed and dailyRewardStreaks

### ISSUE THREAD

**Issue by MattW-source** [MattW-source/discord-wilfred#412]
The cookies option sometimes availible in daily does not update dailyRewardClaimed and dailyRewardStreaks casuing people to potentially lose their streak.

**Comment by MattW-source** [comment]
Assign @MM-coder

**Comment by MM-coder** [comment]
A PR has already been submitted

**Comment by MM-coder** [comment]
Just read the PR closure, target 360 make method, understood.

**Comment by MattW-source** [comment]
Target 361, not 360.

**Comment by MM-coder** [comment]
Targeted 361 as requested, also implemented changes left in old PR

**Comment by MattW-source** [comment]
Closed by #415
