### ISSUE TITLE
Make Command Parameters and Invalid Permissions Error Messages more Consistent

### ISSUE THREAD

**Issue by volcanicer** [MattW-source/discord-wilfred#429]
Currently, there are numerous inconsistencies with command parameters and invalid permissions error messages as shown below:

**Commands Parameters**
- user: 2 (badge, profile)
- target: 3 (balance, coinflip, cookie)
- targetMember: 3 (economy, pay, xp)

A suitable solution to these would be to replace instances of `user` and `targetMember` with `target` to be more consistent with parameter names while needing a less amount of work.

**Invalid Permissions Error Messages**
- "**Invalid Permissions:** This command requires permission rank `RANK`": 5 (badge, economy, multiplier, poll, raffle)
- discord_error(): 1 (xp)
- Other: 1 (setmessage)

A suitable solution to these would be to make all invalid permissions messages to the former since there are more instances of that throughout the bot.

**Comment by MattW-source** [comment]
Completely forgot to assign this. Will assign it to wilfred-370 which I am targeting for Early Feb 2021
