### ISSUE TITLE
Start using converters & arguments

### ISSUE THREAD

**Issue by MattW-source** [MattW-source/discord-wilfred#6]
The current method of getting args out of commands is inefficient and messy. We should start changing commands to use converters and arguments instead of trying to process args ourselves.

**Comment by volcanicer** [comment]
If no one's started on this, I could done this hopefully by the end of the day or by tomorrow evening since this looks like it's going to take a while.

**Comment by MM-coder** [comment]
I'm happy to lend a hand if you wish

**Comment by MattIBM** [comment]
Moved to **wilfred-360** as this is a slightly more time consuming task

**Comment by volcanicer** [comment]
This task is very time consuming and I won't be able to get it done this weekend. Perhaps we could push for 3.7.0?

**Comment by volcanicer** [comment]
Due to recent events, I will no longer be able to work on this PR. If someone else would like to take it up, that would be great.
